import api from './axios'

export default {
  list: (params) => api.get('/transactions', { params }),
  show: (id) => api.get(`/transactions/${id}`),
  create: (data) => api.post('/transactions', data),
  inviter: (id, data) => api.post(`/transactions/${id}/inviter`, data),
  sendMessage: (id, data) => api.post(`/transactions/${id}/messages`, data),
  messages: (id) => api.get(`/transactions/${id}/messages`),
  addDocument: (id, data) => api.post(`/transactions/${id}/documents`, data),
  documents: (id) => api.get(`/transactions/${id}/documents`),
  telechargerDocument: (id, docId) => api.get(`/transactions/${id}/documents/${docId}/telecharger`, { responseType: 'blob' }),
  intervenants: (id) => api.get(`/transactions/${id}/intervenants`),
  verifierIdentite: (id, data) => api.post(`/transactions/${id}/verifier-identite`, data),
  assignerGeometre: (id, data) => api.post(`/transactions/${id}/assigner-geometre`, data),
  validerDossier: (id) => api.post(`/transactions/${id}/valider`),
  avancerEtape: (id) => api.post(`/transactions/${id}/avancer`),
  genererActeVente: (id) => api.post(`/transactions/${id}/generer-acte`),
  exportPdf: (id) => api.post(`/transactions/${id}/export-pdf`, {}, { responseType: 'blob' }),
  accepterInvitation: (id, intervenantId) => api.post(`/transactions/${id}/invitations/${intervenantId}/accepter`),
  refuserInvitation: (id, intervenantId) => api.post(`/transactions/${id}/invitations/${intervenantId}/refuser`),
  rapportGeometre: (id, interventionId, data) => api.post(`/transactions/${id}/interventions/${interventionId}/rapport`, data),
  validerPartie: (id) => api.post(`/transactions/${id}/valider-partie`),
  noterProfessionnel: (id, data) => api.post(`/transactions/${id}/noter`, data),
  suspendre: (id) => api.post(`/transactions/${id}/suspendre`),
  reouvrir: (id) => api.post(`/transactions/${id}/reouvrir`),
}
